### ISSUE TITLE
When uglyurls = true

### ISSUE THREAD

**Issue by nish** [tosi29/inkblotty#1]
I have seen the theme is not correctly appending .html to tags and categories when 

uglyurls = true

This happens on the sidebar and on the posts where ever the tags and categories are listed.

**Comment by tosi29** [comment]
Thank you for your report.
I tried to fix this issue, and probably sidebar works fine now.
You can get fixed version from master branch.

However, I cannot find good solution for post tags/categories in a short time.

1. Do you know any reference themes which work well with "uglyurls = true" ?
    It may be very helpful to fix it.
2. If you know good solution for this issue, please let me know.

Thanks,
tosi

**Comment by nish** [comment]
This is how I have fixed it, Do let me know whether the code is clean because I am not really a coder :)

Please ignore the span class since it is linked to my custom.css file.

```
            {{ $taxo := "categories" }}
            <span class="post-categories">
                {{ range .Param $taxo }}
                    {{ $name := . }}
                    {{ with $.Site.GetPage (printf "/%s/%s" $taxo ($name | urlize)) }}
                        <a href="{{ .Permalink }}">{{ $name }}</a>
                    {{ end }}
                {{ end }}
            </span>

            {{ $taxo := "tags" }}
            <span class="post-tags">
                {{ range .Param $taxo }}
                    {{ $name := . }}
                    {{ with $.Site.GetPage (printf "/%s/%s" $taxo ($name | urlize)) }}
                        <a href="{{ .Permalink }}">{{ $name }}</a>
                    {{ end }}
                {{ end }}
            </span>
```

**Comment by tosi29** [comment]
Thank you for information.
I'm not a specialist of Hugo, so your patch is very helpful to fix.

Unfortunately, it looks not working with multibyte characters, but I got a hint from your code.
I push fixed version to master branch, so please try it if you want.

Thanks,
tosi

**Comment by nish** [comment]
Thank you, I did not test multibyte characters.

I will test it and let you know how it goes. I use your theme to build my custom code on top of it so whenever I find issues, I will open an issue so it can be fixed.

Thanks

**Comment by tosi29** [comment]
I close this issue.
If you find any problem or side effects, please open this or new issue.

Thank you for your contribution.
