### ISSUE TITLE
favicon対応

### ISSUE THREAD

**Issue by rkarsnk** [tosi29/inkblotty#14]
独自のfaviconを導入できるようにする。

#### 最低限
ブラウザのタブやお気に入りバーでfaviconが表示できるようにする。

#### 可能なら
スマホのホーム画面にショートカットを置いたときに、faviconがアイコンになるようにする(App Icon対応)。

### 実現方法
head.htmlにfaviconに関する記述を追加する？

### 検討すべき事項
faviconファイルが存在しない場合の対策

**Comment by tosi29** [comment]
ありがとうございます、良いと思います！

> #### 最低限
> ブラウザのタブやお気に入りバーでfaviconが表示できるようにする。
> #### 可能なら
> スマホのホーム画面にショートカットを置いたときに、faviconがアイコンになるようにする(App Icon対応)。
> ### 実現方法
> head.htmlにfaviconに関する記述を追加する？

favicon対応だけであれば、比較的容易かなと思います。
faviconとスマホ向けアイコンを共通化できればベストですが、なかなか厄介だったような記憶が…。
この辺りは複雑なので、要調査ですね。


> ### 検討すべき事項
> faviconファイルが存在しない場合の対策

以下を使用すれば、ファイルが存在する場合のみタグを追加するようにできそうかな、と思いました。
https://gohugo.io/functions/fileexists/

**Comment by rkarsnk** [comment]
マージされたのでクローズしますね。
