### ISSUE TITLE
Cosmetic issue when html minified

### ISSUE THREAD

**Issue by nish** [tosi29/inkblotty#2]
I have seen a slight issue with the summery.html layouts/_default/summary.html file

"Read more " line 31

`<a href="{{ .RelPermalink }}" class="more-link">Read more </a>
`

When hugo is generated with --minify option, it removes the space and the css code sits right next to it.

I have fixed that code by replacing the line without space.

`<a href="{{ .RelPermalink }}" class="more-link">Read more</a>
`

and add the following to style.css

```
.more-link::after {
    font: 100%/1 awesome;
    content: '\f138';
    margin-left: 5px;
}
```

**Comment by tosi29** [comment]
Thank you for your report. It looks working fine!
I pushed this fix to master branch.

Regarding `margin-left: 5px;`, I implemented it in `custom.css`.
Because I'd like to keep original `style.css` which comes from other work.

Thank you very much for your contribution!

Thanks,
tosi
