### ISSUE TITLE
Pagination & Title

### ISSUE THREAD

**Issue by nish** [tosi29/inkblotty#3]
I have seen two issues with this theme running Hugo version 0.69.2 with UglyURL turned on.

The links on the Pagination at the bottom is homepage is showing as **/page/1/** etc instead of **/page/1.html**

Also when it displays **/page/1/** it is showing the wrong Title tag on the homepage. It is displaying the Title Tag as **- title** instead of **title**. Please note that you are calling title from config.toml

This issue seems to be intermittent so I had to run hugo server a few times to see this error generated.

It should be a Hugo issue but I want to make you aware of this problem.

**Comment by tosi29** [comment]
I tried `hugo server` command about 20 times with hugo 0.69.2, but I couldn't reproduce it...
It might be difficult to investigate for me.

By the way, is it reproducible with other theme?
Probably it is helpful to know the root cause is hugo side or theme side.

**Comment by tosi29** [comment]
The following is just for reference about uglyurls. (for myself in the future)

- `exampleSite` does not work with `uglyurls = true`. 
  - Build (`hugo`) failed with errors.
  - Preview `hugo server` looks working fine... why?
- According to official reference, uglyurls flag can be controlled by command line.
  But actually, neither `hugo --uglyURLs` nor `hugo --uglyURLs=true` does not work.
  https://gohugo.io/content-management/urls/#ugly-urls
- If `url` is specified at front matter of md file, uglyurl is `url` only. (`.html` is not appended)
- If `slug` is specified at front matter of md file, uglyurl is `slug` + `.html`.

**Comment by nish** [comment]
> I tried `hugo server` command about 20 times with hugo 0.69.2, but I couldn't reproduce it...
> It might be difficult to investigate for me.
> 
> By the way, is it reproducible with other theme?
> Probably it is helpful to know the root cause is hugo side or theme side.

I can reproduce this on my side, it is very strange that you can't reproduce it.

I think it looks like it has nothing to do with the pagination since I replaced it with Hugo's internal pagination template.

It points to me, the issue looks like an issue with Hugo itself.

**Comment by nish** [comment]
I have found the cause of the problem. It looks like if you use internal pagination, it is displaying this error. I guess the problem is not related to this template since you are using your own pagination code.

It would be helpful if you try and use internal pagination on your list.html and see whether you can find the solution for this problem...

`{{ template "_internal/pagination.html" . }}
`

**Comment by tosi29** [comment]
Thank you for additional information.
I understood that it maybe comes from your customize.

I tried to reproduce the problem about 10 times, but I couldn't.
- Set `uglyurls = true` in config.toml
- Replace pagination with `{{ template "_internal/pagination.html" . }}` in list.html
- Run `hugo server`
- See list pages, but pagination links look correct. Link destination suffix is `.html`
- Click pagination link, and it works
I think it looks difficult to reproduce...

How often you can see this problem?
If you have other computer, I'd like to know whether this problem is reproducible or not on the machine.

**Comment by nish** [comment]
Hi Tosi, thank you for the time you spend to investigate the problem.

I have done the following...

- I have tested on both Windows 10 and Mac running Hugo version 0.71.1
- I have removed `uglyurl = true` statement to rule out the problem.
- I am running a forked version of your template under https://github.com/nish/inkblotty with a sample config located in that repo.
- I am seeing this error very common when I build the code via `hugo` and checking the index.html file. 8/10
- I will see the issue popping up time to time when I run hugo server (3/10)

Do let me know if I could help any further to find the cause of the bug.

**Comment by nish** [comment]
I think I found the cause of the problem. It is not the template. It was the_index.md file which sits within the content folder. The content had two sections and within each section the fle had the following info. 

`+++
url = “/“
+++`

It should have been (section = name of the section)

`+++
url = “/section”
+++`

Please close this issue and thank you.

**Comment by tosi29** [comment]
That's good to hear! Thank you for report.
