### ISSUE TITLE
トップページヘッダーのh1について

### ISSUE THREAD

**Issue by rkarsnk** [tosi29/inkblotty#4]
GitHubのIssueに関して不慣れですが、Issue出させていただきます。

Hugoで生成したサイトのトップページにアクセスすると、図１のように、menuの下部にBlogのタイトルが表示されてしまいます。

<figure>
<figcaption>図1 homepage-headerあり</figcaption>
<img src="https://user-images.githubusercontent.com/26945036/103257289-f6a70480-49d3-11eb-832e-73a41f9a8ea6.jpg" width=200>
</figure>

試しに、`inkblotty/layouts/index.html` の <header class = "homepage-header">部分をコメントアウトすると、図２のようになりました。
```
{{ define "main" }}
{{ $paginator := .Paginate ( where .Site.RegularPages "Type" "post" ) 10 }}
<main aria-role="main">
<!--
  <header class="homepage-header">
    <h1>{{.Title}}</h1>
    {{ with .Params.subtitle }}
    <span class="subtitle">{{.}}</span>
    {{ end }}
  </header>
-->
  <div class="homepage-content">
```

<figure>
<figcaption>図2 homepage-headerなし</figcaption><img src="https://user-images.githubusercontent.com/26945036/103257291-f9095e80-49d3-11eb-8afe-773475eafb8b.jpg" width=200>
</figure>

Wordpress のInkblotのテーマでもトップページでは図２のように表示されていますので、改修ご検討おねがいします。

上の修正で、他のページに大きな影響がないことは簡単に確認しましたが、Hugo テンプレートについて未だ勉強中ですので、Pull Requestを出すのはやめておきます・・・

**Comment by tosi29** [comment]
ご報告ありがとうございます。

いただいた情報をもとに、こちらでも検証してみました。
その結果、以下のことが確認できました。
* トップページにて、タイトルがメニュー下部にも表示されてしまう
* 提示いただいたように`inkblotty/layouts/index.html`を修正すると
  * `inkblotty/layouts/index.html`で定義されるトップページでは、menu下部にタイトルが表示されなくなる
  * `inkblotty/layouts/_default/list.html`で定義される画面（カテゴリやタグでフィルタして表示する画面）では、これまで通りmenu下部にカテゴリ名やタグ名が表示される

そのため先ほど変更をpushしましたので、最新のmasterブランチをご利用ください。

> 上の修正で、他のページに大きな影響がないことは簡単に確認しましたが、Hugo テンプレートについて未だ勉強中ですので、Pull Requestを出すのはやめておきます・・・

私もHugoテンプレートについては今でも修行中の身ですので、お気になさらず…！
修正案だけでなくWordpressの既存動作まで確認いただけたので、こちらとしては大変助かりました。
ありがとうございました！
