### ISSUE TITLE
Mobile Menu Issues

### ISSUE THREAD

**Issue by nish** [tosi29/inkblotty#6]
When you load the page via a mobile device, the menu does not work as it should be.

See the example below... 

You can go from / (Home) to About or Contact. But when you are in About or Contact, you cannot go back to Home.

```
[[menu.main]]
  identifier = "Home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/go/about"
  weight = 10

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/go/contact"
  weight = 11
```

**Comment by tosi29** [comment]
@nish 
Current page is judged by comparing URLs.
* Absolute URL of Permalink
* Absolute URL of "url"

Probably, your Permalink end with slash.

The following should work fine.
```
[[menu.main]]
  identifier = "Home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/go/about/"
  weight = 10

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/go/contact/"
  weight = 11
```

**Comment by nish** [comment]
Very good spot, thank you.
